config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :name, :author, :isbn, :price, :category, presence: true
	validates :name, :isbn, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
	before_action :find_book, only: [:edit, :update, :destroy]

	#Render index page
	#
	#Displaying all books
	def index
		coditions = ''
		if params[:query].present?
			qry = params[:query].downcase 	
			coditions = ["lower(name) LIKE ? OR lower(author) LIKE ? OR lower(isbn) LIKE ?", "%#{qry}%", "%#{qry}%", "%#{qry}%"]
		end
		
		default_sort = params[:sort].present? ? params[:sort] : 'name'
		default_order = params[:direction].present? ? params[:direction] : 'asc' 
		@books = Book.where(coditions).order(default_sort + ' ' + default_order)
		respond_to do |format|
      		format.html # show.html.erb
      		format.js { 
      			render 'list'
      		 }
    	end
	end

	#Render new page
	#
	#Displaying new book page
	def new
		@book = Book.new
	end

	#Create a book.
	#
	#Create a book.
	def create
		@books = Book.new(book_params)
		if @books.save
			flash[:notice] = t('common.created_successfully', model_name: Book.name)
			redirect_to books_path
		end	
	end

	def edit
		#Rendering edit page.
	end

	#Update a book.
	#
	#Update a book.
	def update
		@book.update_attributes(book_params)
		if @book
			flash[:notice] = t('common.updated_successfully', model_name: Book.name)
			redirect_to books_path
		end
	end

	#Render destroy method
	#
	#Destroy the book
	def destroy
		if @book.destroy
			flash[:notice] = t('common.deleted_successfully', model_name: Book.name)
			redirect_to books_path
		end
	end

	private
		
		def find_book
			@book = Book.find_by(id: params[:id])
		end

		def book_params
			params.require(:book).permit(:name, :author, :isbn, :price, :category, :publish)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, sort: column, direction: direction
  end
  
end

app/views/books/_form.html.erb
<h1>Book Register</h1>
<%= simple_form_for @book, html: { class: 'form-horizontal' } do |f| %>
	<%= f.input :name %>
	<%= f.input :author %>
	<%= f.input :isbn %>
	<%= f.input :price %>
	<%= f.input :category %>
	<%= f.input :publish, as: :boolean %>
	<%= f.submit 'Save'%>
<% end %>
<%= link_to 'Back', books_path, class: 'btn btn-primary'
 %>

app/views/books/_list.html.erb
<h2>List Books</h2>
            
  <table class="table">
    <thead>
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "author" %></th>
        <th><%= sortable "isbn" %></th>
        <th><%= sortable "price" %></th>
        <th><%= sortable "category" %></th>
        <th><%= sortable "publish" %></th>
        <th>Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to book.name, edit_book_path(book) %></td>
          <td><%= book.author %></td>
          <td><%= book.isbn %></td>
          <td><%= book.price.to_f %></td>
          <td><%= book.category %></td>
          <td><%= book.publish == true ? 'Y' : 'N'%></td>
          <td><%= link_to 'Delete', 
             book_path(book), 
                         method: :delete, 
                         data: { confirm: t('destroy_msg') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<%= form_tag(books_path, method: :get, remote: true ) do %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<div class= 'books_div'>
  <%= render 'list' %>
</div>

<%= link_to 'New book', new_book_path, class: 'btn btn-primary'
 %>

app/views/books/list.js.erb
$('.books_div').html("<%= j render( partial: 'books/list', locals: {books: @books}) %>");

app/views/books/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>